common/models/Apply.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "wd_apply".
 *
 * @property integer $id
 * @property integer $applicant_id
 * @property integer $vacancy_id
 * @property string $cv_profile
 * @property string $cv_upload
 * @property string $cv
 * @property string $date_time
 * @property string status
 * 
 */
class Apply extends \yii\db\ActiveRecord
{
	
	public $from;
	public $to;
	
    /**
     * @inheritdoc
     */
	
	public $referrer;
	
    public static function tableName()
    {
        return 'wd_apply';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['applicant_id', 'vacancy_id', 'date_time'], 'required'],
        	[['status'],'string'],
        	['cv','file','maxSize' => 512000, 'tooBig' => 'Limit is 500KB','extensions' => 'pdf, docx'],
        	[['cv_profile'],'myRequired'],
        	[['cv_upload'],'notRequired'],
            [['applicant_id', 'vacancy_id',], 'integer'],
            [['date_time'], 'safe'],
        		['to',
        		'compare',
        		'compareAttribute'=>'from',
        		'operator'=>'>',
        		],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'applicant_id'	 => 'Applicant',
            'vacancy_id'	 => 'Vacancy Post',
        	'cv_upload' 	 => 'Upload CV',
        	'cv_profile'	 => 'CV from Profile',
            'date_time' 	 => 'Applied Date',
        	'cv'			 => 'CV',
        	'status'		 => 'Status',
        	'email'			 => 'Email'
        	
        ];
    }
      
    public function getUsername()
    {
    	return $this->hasOne(FrontendUser::className(), ['id'=>'applicant_id']);
    }
    
    public function getVacancyname()
    {
    	return $this->hasOne(Vacancy::className(), ['vacancy_id'=>'vacancy_id']);
    }
    
    public function myRequired($attribute_name, $params)
    {
    	if (!$this->hasErrors()) {
    		if ($this->cv_profile == 0 && $this->cv_upload == 0 ) {
    			$this->addError($attribute_name, Yii::t('writesdown', 'Atleast select 1 of the field must be selected'));
    			return false;
    		}
    	}
    	return false;
    }
    
    public function notRequired($attribute_name, $params)
    {
    	if (!$this->hasErrors()) {
    		if ($this->cv_profile == 1 && $this->cv_upload == 1 ) {
    			$this->addError($attribute_name, Yii::t('writesdown', 'Only 1 of the field must be selected'));
    			return false;
    		}
    	}
    	return false;
    }
    
}

backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use common\models\LoginForm;
use common\models\Option;
use common\models\PasswordResetRequestForm;
use common\models\Post;
use common\models\PostComment;
use common\models\ResetPasswordForm;
use common\models\SignupForm;
use common\models\User;
use Yii;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use Facebook\FacebookRequest;
use Facebook\Facebook;
use Facebook\Authentication\OAuth2Client;
use Facebook\Exceptions\FacebookResponseException;
use Facebook\Exceptions\FacebookSDKException;
use common\models\Status;

/**
 * Site controller.
 *
 * @author  Tika Raj Shrestha <tika.raj@bentraytech.com>
 * @since   0.1.0
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'login',
                            'request-password-reset',
                            'reset-password',
                            'forbidden',
                            'not-found',
                            'terms',
                            'sms',
                        ],
                        'allow'   => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'error','post','fb-login','statuspost','upgrade'],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                    [
                        'actions'       => ['signup'],
                        'allow'         => true,
                        'matchCallback' => function () {
                            return Option::get('allow_signup') && Yii::$app->user->isGuest;
                        },
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        		'auth' => [
        				'class' => 'yii\authclient\AuthAction',
        				'successCallback' => [$this, 'oAuthSuccess'],
        		],
        ];
    }
    public function actionSms(){
        $sms = Yii::$app->sms;
        try{
            return $sms->send(['9849645936'],'check message ss');
        }
        catch(\Exception $exception){
            throw $exception;
        }
        
    }

    public function oAuthSuccess($client) {
    	// get user data from client
    	$userAttributes = $client->getUserAttributes();
    
    	// do some thing with user data. for example with $userAttributes['email']
    }
     public function actionFbLogin($id){
    	$fb = new Facebook([
    			'app_id' => '775416375896967',
    			'app_secret' => 'd84234684725488849ed891802027617',
    			'default_graph_version' => 'v2.5',
    	]);
    	
    	$helper = $fb->getRedirectLoginHelper();
    	$permissions = ['email', 'user_likes','user_posts','publish_actions'];  // optional
    	$loginUrl = $helper->getLoginUrl('http://localhost/bentray-cms/admin/site/post?id='.$id, $permissions);
    	return $this->render('fblofin',['loginUrl'=>$loginUrl]);
    	
    	
    	
    } 
    public function actionPost($id){
  
    	
    	 $fb = new Facebook([
    			'app_id' => '775416375896967',
    			'app_secret' => 'd84234684725488849ed891802027617',
    			'default_graph_version' => 'v2.2',
    	]);
    	
		
		$helper = $fb->getRedirectLoginHelper();
		
		try {
		  $accessToken = $helper->getAccessToken();
		} catch(FacebookResponseException $e) {
		  // When Graph returns an error
		  echo 'Graph returned an error: ' . $e->getMessage();
		  exit;
		} catch(FacebookSDKException $e) {
		  // When validation fails or other local issues
		  
		  echo 'Facebook SDK returned an error: ' . $e->getMessage();
		  exit;
		}
		
		if (! isset($accessToken)) {
		  if ($helper->getError()) {
		    header('HTTP/1.0 401 Unauthorized');
		    echo "Error: " . $helper->getError() . "\n";
		    echo "Error Code: " . $helper->getErrorCode() . "\n";
		    echo "Error Reason: " . $helper->getErrorReason() . "\n";
		    echo "Error Description: " . $helper->getErrorDescription() . "\n";
		  } else {
		    header('HTTP/1.0 400 Bad Request');
		    echo 'Bad request';
		  }
		  exit;
		}
		
		
		// The OAuth 2.0 client handler helps us manage access tokens
		$oAuth2Client = $fb->getOAuth2Client();
		
		// Get the access token metadata from /debug_token
		$tokenMetadata = $oAuth2Client->debugToken($accessToken);
	
		// Validation (these will throw FacebookSDKException's when they fail)
		$tokenMetadata->validateAppId('775416375896967'); // Replace {app-id} with your app id
		// If you know the user ID this access token belongs to, you can validate it here
		//$tokenMetadata->validateUserId('123');
		$tokenMetadata->validateExpiration();
		
		if (! $accessToken->isLongLived()) {
		  // Exchanges a short-lived access token for a long-lived one
		  try {
		    $accessToken = $oAuth2Client->getLongLivedAccessToken($accessToken);
		  } catch (FacebookSDKException $e) {
		    echo "<p>Error getting long-lived access token: " . $helper->getMessage() . "</p>\n\n";
		    exit;
		  }
		
		  echo '<h3>Long-lived</h3>';
		  var_dump($accessToken->getValue());
		}
		
		$_SESSION['fb_access_token'] = (string) $accessToken;
		$acctoken = $_SESSION['fb_access_token'];
	
	     $status = Status::find()->where(['status_id'=>$id])->one();
		  $linkData = [
				'message' => $status->details,
		];
		
		try {
			// Returns a `Facebook\FacebookResponse` object
			$response = $fb->post('/me/feed', $linkData, $acctoken);
			
		} catch(FacebookResponseException $e) {
			echo 'Graph returned an error: ' . $e->getMessage();
			exit;
		} catch(FacebookSDKException $e) {
			echo 'Facebook SDK returned an error: ' . $e->getMessage();
			exit;
		}
		
		$graphNode = $response->getGraphNode();
		
	//	echo 'Posted with id: ' . $graphNode['id'];  
		return $this->redirect('statuspost');

    	
    }
    public function actionStatuspost()
    {
    	return $this->render('statuspost');
    }
    
    
    /**
     * Show user count, post count, post-comment count on index (dashboard).
     *
     * @return string
     */
    public function actionIndex()
    { 	
        // Get list User model
        $userQuery = User::find()->andWhere(['status' => '10']);
        $userCloneQuery = clone $userQuery;
        $userCount = $userCloneQuery->count();
        $users = $userQuery->limit(8)->orderBy(['id' => SORT_DESC])->all();
        // Get list Post model
        $postQuery = Post::find()->andWhere(['post_status' => 'publish']);
        $postCloneQuery = clone $postQuery;
        $postCount = $postCloneQuery->count();
        $posts = $postQuery->limit(5)->orderBy(['id' => SORT_DESC])->all();
        // Get list PostComment model
        $commentQuery = PostComment::find()->andWhere(['comment_approved' => 'approved']);
        $commentCloneQuery = clone $commentQuery;
        $commentCount = $commentCloneQuery->count();
        $comments = $commentQuery->limit(3)->orderBy(['id' => SORT_DESC])->all();

        return $this->render('index', [
            'users'        => $users,
            'posts'        => $posts,
            'comments'     => $comments,
            'userCount'    => $userCount,
            'postCount'    => $postCount,
            'commentCount' => $commentCount,
        ]);
    }

    /**
     * Show login page and process login page.
     *
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        // Set layout and bodyClass for login-page
        $this->layout = 'blank';
        Yii::$app->params['bodyClass'] = 'login-page';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        return $this->render('login', [
            'model' => $model
        ]);
    }

    /**
     * Logout for current user and redirect to home of backend.
     *
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Show signup for guest to register on site while Option::get('allow_signup') is true.
     *
     * @return string|\yii\web\Response
     */
    public function actionSignup()
    {
        // Set layout and body class of register-page
        $this->layout = 'blank';
        Yii::$app->params['bodyClass'] = 'register-page';
        $model = new SignupForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Generate and send token to user's email for resetting password.
     *
     * @return string|\yii\web\Response
     */
    public function actionRequestPasswordReset()
    {
        // Change layout and body class of register page
        $this->layout = 'blank';
        Yii::$app->params['bodyClass'] = 'register-page';
        $model = new PasswordResetRequestForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

frontend/views/site/contact.php
<?php
/**
 * @link      http://www.writesdown.com/
 * @author    Agiel K. Saputra <13nightevil@gmail.com>
 * @copyright Copyright (c) 2015 WritesDown
 * @license   http://www.writesdown.com/license/
 */

use common\models\Option;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

$this->title = Yii::t('writesdown', 'Contact') . ' - ' . Option::get('sitetitle');
$this->params['breadcrumbs'][] = Yii::t('writesdown', 'Contact');
?>
<div class="single site-contact">
    <article class="hentry">
        <header class="entry-header page-header">
            <h1 class="entry-title"><?= Html::encode(Yii::t('writesdown', 'Contact')) ?></h1>

        </header>
        <div class="entry-content">
            <p>
                <?= Yii::t(
                    'writesdown',
                    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.'
                ) ?>

            </p>

            <?php $form = ActiveForm::begin(['id' => 'contact-form']) ?>

            <?= $form->field($model, 'name') ?>

            <?= $form->field($model, 'email') ?>

            <?= $form->field($model, 'subject') ?>

            <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

            <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
            ]) ?>

            <div class="form-group">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>

            </div>
            <?php ActiveForm::end() ?>

        </div>
    </article>
</div>

frontend/views/site/cv.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
$this->title = Yii::t ( 'writesdown', 'CV REQUIRED' );
?>



<div class="box-4 box-5 wow bounceInUp desc" data-wow-delay="0.4s">
			
	<div class="head-section text-left wow bounceIn" style="text-transform: uppercase;"
				data-wow-delay="0.4s">
				<h4>
					<b><?= Html::encode($this->title).' / '.$model->vacancyname->vacancy_title;?></b>
				</h4>
			</div>
	<div class="confirm-form" style="margin-top: 10px;">
	<div class="panel panel-default">
	<div class="panel-body">
			<?php $form = ActiveForm::begin([
					'id'=>'cv-form',
					'options' => ['enctype' => 'multipart/form-data']
			]); ?>
			
			<?= $form->field($model, 'cv_profile')->checkbox() ?>
			
			<?= $form->field($model, 'cv_upload')->checkbox(['class'=>'abc']) ?>
			
			<div class="xyz" style="display: none">
			<?= $form->field($model, 'cv')->fileinput() ?>
			</div>
			
			<div class="form-group">
			<?= Html::submitButton('Submit', ['class' => 'btn btn-success']) ?>
        	
    		</div>

			<?php ActiveForm::end(); ?>
			</div>
			</div></div>
			
</div>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("#apply-cv_upload").click(function () {
            if ($(this).is(":checked")) {
                $(".xyz").show();
            } else {
                $(".xyz").hide();
            }
        });
    });
</script>

frontend/views/site/error.php
<?php
/**
 * @link      http://www.writesdown.com/
 * @author    Agiel K. Saputra <13nightevil@gmail.com>
 * @copyright Copyright (c) 2015 WritesDown
 * @license   http://www.writesdown.com/license/
 */

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
$this->params['breadcrumbs'][] = $this->title;
$this->registerMetaTag([
    'name'    => 'robots',
    'content' => 'noindex, nofollow',
]);
?>
<div class="site-error">
    <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger"><?= nl2br(Html::encode($message)) ?></div>
    <p>The above error occurred while the Web server was processing your request.</p>
    <p>Please contact us if you think this is a server error. Thank you.</p>
</div>

frontend/views/site/login.php
<?php
/**
 * @file      login.php.
 * @date      6/4/2015
 * @time      5:36 AM
 * @author    Agiel K. Saputra <13nightevil@gmail.com>
 * @copyright Copyright (c) 2015 WritesDown
 * @license   http://www.writesdown.com/license/
 */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use codezeen\yii2\adminlte\widgets\Alert;
use codezeen\yii2\tinymce\TinyMce;
use yii\bootstrap\Modal;
use yii\captcha\Captcha;

/* MODEL */
use common\models\Option;
use yii\helpers\Url;
use yii\captcha\CaptchaAction;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Login';
$this->params ['breadcrumbs'] [] = $this->title;
$this->registerCssFile ( Url::to ( [ 
		'/css/widgets/responsiv-table.css' 
] ), [ 
		'depends' => [ 
				\frontend\assets\AppAsset::className () 
		] 
] );

?>

<div class="login-form vacancy">
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="row">
				<div class="col-md-5" style="margin-left: 3.7%;">
							<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
        <p style="margin-left: 4px;">
						<b><?= Yii::t('writesdown', 'Sign in to start your session'); ?></b>
					</p>
					<hr>					
        <?= $form->field($model, 'username', ['template' => '<div class="form-group has-feedback">{input}<span class="glyphicon glyphicon-user form-control-feedback"></span></div>{error}'])->textInput(['placeholder' => $model->getAttributeLabel('username')]); ?>
					
		
		<?= $form->field($model, 'referrer')->hiddenInput()->label(false); ?>
	
		
        <?= $form->field($model, 'password', ['template' => '<div class="form-group has-feedback">{input}<span class="glyphicon glyphicon-lock form-control-feedback"></span></div>{error}'])->passwordInput(['placeholder' => $model->getAttributeLabel('password')]); ?>
	
							
                			<?= $form->field($model, 'rememberMe')->checkbox()?>
            			
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary btn-block btn-flat'])?><br>
                
                <?= Html:: a('Forgot Password',['site/forgotpassword'])?>		<br>
					<br>				
									
  	    	   	<?= Html::a('I am not a member, Register.', ['site/signup']) ?> <br>
					<br>
            			
        <?php ActiveForm::end(); ?>

        <br />



				</div>
				<div class="col-md-1"></div>
				<div class="col-md-5">
			<?php if (! $_GET ['id'] ){			
			}else{ ?>
					<div class="guest-form-body">
						
						<?php $form = ActiveForm::begin([
								'id'=>'login-guest',
								'action'=>Url::to(['/guest/send','id'=>$_GET ['id']]),
								'options'=>['enctype'=>'multipart/form-data'],	
						]); ?>			
								
						<p style="margin-left: 4px;">
							<b><?= Yii::t('writesdown', 'Apply without signing up'); ?></b>
						
						
						</h4>
						<hr>

						<?=$form->field	( $gmodel, 'vacancy_id',[ 'template' => '<div class="form-group has-feedback">{input}</div>{error}' ] )->hiddenInput();?>
						
						<?=$form->field ( $gmodel, 'name', 		[ 'template' => '<div class="form-group has-feedback">{input}<span class="glyphicon glyphicon-user form-control-feedback"></span></div>{error}' ] )->textInput ( [ 'placeholder' => $gmodel->getAttributeLabel ( 'Full Name' ) ] );?>
						
						<?=$form->field ( $gmodel, 'email', 	[ 'template' => '<div class="form-group has-feedback">{input}<span class="glyphicon glyphicon-envelope form-control-feedback"></span></div>{error}' ] )->textInput ( [ 'placeholder' => $gmodel->getAttributeLabel ( 'Email Address' ) ] );?>
						
						<?=$form->field ( $gmodel, 'phone', 	[ 'template' => '<div class="form-group has-feedback">{input}<span class="glyphicon glyphicon-phone form-control-feedback"></span></div>{error}' ] )->textInput ( [ 'placeholder' => $gmodel->getAttributeLabel ( 'Phone no.' ) ] );?>
						
						<?=$form->field ( $gmodel, 'address', 	[ 'template' => '<div class="form-group has-feedback">{input}<span class="glyphicon glyphicon-home form-control-feedback"></span></div>{error}' ] )->textInput ( [ 'placeholder' => $gmodel->getAttributeLabel ( 'Address' ) ] );?>
						
						<?=$form->field ( $gmodel, 'message',	[ 'template' => '<div class="form-group has-feedback">{input}</div>{error}' ])->textarea(['rows' => 6, 'placeholder' => $model->getAttributeLabel ( 'Write something about yourself' ) ]) ?>    
						
						<?= $form->field( $gmodel, 'cv')->fileInput(); ?>
						

						
						<?= $form->field( $gmodel, 'verificationCode')->widget(Captcha::className([
								'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
						]))->hint('Click on the captcha to refresh') ?>
						
						<div class="form-group">
     						<?= Html::submitButton('Submit', ['class' => 'btn btn-primary btn-block btn-flat'])?>
    					</div>
		
			<?php ActiveForm::end(); ?>
					
					</div>
			<?php } ?>
			</div>

			</div>
		</div>
	</div>
</div>

<!--
	<script type="text/javascript">
    window.onload = setupRefresh;

    function setupRefresh() {
      setTimeout("refreshPage();", 3000); // milliseconds
    }
    function refreshPage() {
       window.location = location.href;
    }
  </script> 
-->

  

<?php
										Modal::begin ( [ 
												'header' => '<h4 align="center">Please fill out your email. A link to reset password will be sent there.</h4>',
												'id' => 'modal5',
												'size' => 'modal-md',
												'clientOptions' => [ 
														'backdrop' => 'static',
														'keyboard' => false 
												] 
										] );
										echo "<div id='modalContent5'></div>";
										Modal::end ();
										?>

frontend/views/site/search.php
<?php
/**
 * @link      http://www.writesdown.com/
 * @author    Agiel K. Saputra <13nightevil@gmail.com>
 * @copyright Copyright (c) 2015 WritesDown
 * @license   http://www.writesdown.com/license/
 */

use common\models\Option;
use yii\helpers\Html;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $s string */
/* @var $posts common\models\Post[] */
/* @var $tags common\models\Term[] */
/* @var $pages yii\data\Pagination */

$this->title = Html::encode(Yii::t('writesdown', 'Search Result: {s}', ['s' => $s]) . ' - ' . Option::get('sitetitle'));
$this->params['breadcrumbs'][] = Html::encode(Yii::t('writesdown', 'Search Result: {s}', ['s' => $s]));
$this->registerMetaTag([
    'name'    => 'robots',
    'content' => 'noindex, nofollow',
]);
?>

<div class="archive post-index">
    <header id="archive-header" class="archive-header page-header">
        <h1><?= Html::encode(Yii::t('writesdown', 'Search Result: {s}', ['s' => $s])) ?></h1>

    </header>

    <?php if ($posts): ?>
        <?php foreach ($posts as $post): ?>
            <article class="hentry">
                <header class="entry-header page-header">
                    <h2 class="entry-title"><?= Html::a(Html::encode($post->post_title), $post->url) ?></h2>

                    <?php $updated = new \DateTime($post->post_modified, new DateTimeZone(Yii::$app->timeZone)) ?>
                    <div class="entry-meta">
                        <span class="entry-date">
                            <span aria-hidden="true" class="glyphicon glyphicon-time"></span>
                            <a rel="bookmark" href="<?= $post->url ?>">
                                <time datetime="<?= $updated->format('c') ?>" class="entry-date">
                                    <?= Yii::$app->formatter->asDate($post->post_date) ?>
                                </time>
                            </a>
                        </span>
                        <span class="byline">
                            <span class="author vcard">
                                <span aria-hidden="true" class="glyphicon glyphicon-user"></span>
                                <a rel="author" href="<?= $post->postAuthor->url ?>" class="url fn">
                                    <?= $post->postAuthor->display_name ?>
                                </a>
                            </span>
                        </span>
                        <span class="comments-link">
                            <span aria-hidden="true" class="glyphicon glyphicon-comment"></span>
                            <a title="<?= Yii::t(
                                'writesdown',
                                'Comment on {postTitle}',
                                ['postTitle' => $post->post_title]
                            ) ?>" href="<?= $post->url ?>#respond"><?= Yii::t('writesdown', 'Leave a comment') ?></a>
                        </span>
                    </div>
                </header>
                <div class="entry-summary">
                    <?= $post->post_excerpt ?>...
                </div>
                <footer class="footer-meta">
                    <?php $tags = $post->getTerms()->innerJoinWith(['taxonomy'])->andWhere(['taxonomy_name' => 'tag'])->all() ?>

                    <?php if ($tags): ?>
                        <h3>
                            <?php foreach ($tags as $tag): ?>
                                <?= Html::a($tag->term_name, $tag->url, [
                                    'class' => 'btn btn-xs btn-success',
                                ]) . "\n" ?>
                            <?php endforeach ?>
                        </h3>
                    <?php endif; ?>

                </footer>
            </article>
        <?php endforeach ?>
        <nav id="archive-pagination">
            <?= LinkPager::widget([
                'pagination'           => $pages,
                'activePageCssClass'   => 'active',
                'disabledPageCssClass' => 'disabled',
                'options'              => [
                    'class' => 'pagination',
                ],
            ]) ?>
        </nav>
    <?php endif ?>

</div>

frontend/views/site/signup.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use dosamigos\datepicker\DatePicker;
use yii\captcha\Captcha;
/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
$this->title = Yii::t ( 'writesdown', 'Register' );
?>

<div class="signup-form vacancy">
				<div class="panel panel-default">
					<div class="panel-body">
    <?php
				
$form = ActiveForm::begin ( [ 
						'id' => 'signip_form',
						'options' => [ 
								'enctype' => 'multipart/form-data' 
						] 
				] );
				?>
    
    <div class="row">
							<div class="col-md-10">
								<p class="login-box-msg"><b><?= Yii::t('writesdown', 'Sign Up to start your session'); ?></b></p>
								<br>
    <?=$form->field ( $model, 'username' )->textInput ( [ 'maxlength' => 255,'placeholder' => $model->getAttributeLabel ( 'username' ) ] )?>

    <?=$form->field ( $model, 'email' )->input ( 'email', [ 'maxlength' => 255,'placeholder' => $model->getAttributeLabel ( 'email' ) ] )->hint ( Yii::t ( 'writesdown', 'An e-mail used for receiving notification and resetting password.' ) )?>
    
    <?=$form->field ( $model, 'full_name' )->textInput ( [ 'maxlength' => 255,'placeholder' => $model->getAttributeLabel ( 'full_name' ) ] )?>

    <?=$form->field ( $model, 'password' )->passwordInput ( [ 'maxlength' => 255,'placeholder' => $model->getAttributeLabel ( 'password' ) ] )?>
    
    <?=$form->field ( $model, 'repassword' )->passwordInput ( [ 'maxlength' => 255,'placeholder' => $model->getAttributeLabel ( 'repassword' ) ] )?>   <br>
    
 	<?= $form->field($model, 'term_condition')->checkbox([
    'label' => 'I accept the <a href="terms" target="_blank">Terms &nbsp;</a>and Conditions.'
	]);?>
   
    <?= $form->field($model, 'verificationCode')->widget(Captcha::className(),['captchaAction'=>'site/captcha'])?>
   
    
    <div class="form-group">
    
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary'])?>
    </div>
							</div>
						</div>
    <?php ActiveForm::end(); ?>
    </div>
				</div>
				</div>
			
		

	